apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cardealerapi-hpa
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cardealerapi-deployment
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cardealerclient-hpa
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cardealerclient-deployment
  targetCPUUtilizationPercentage: 50