apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardealerclient-deployment
  labels:
    app: cardealerclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardealerclient
  template:
    metadata:
      labels:
        app: cardealerclient
    spec:
      containers:
        - name: cardealerclient
          image: cardealerclient
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: CarDealerAPIUrl
              valueFrom:
                configMapKeyRef:
                  name: cardealerapi-configmap
                  key: cardealerapi_url
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: cardealerclient-service
spec:
  type: NodePort
  selector:
    app: cardealerclient
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 80
      nodePort: 32000             