version: '3.4'

services:
  cardealer.api:
    image: ${DOCKER_REGISTRY-}cardealerapi
    build:
      context: ./Services/CarDealer.API
      dockerfile: Dockerfile

  cardealer.client:
    image: ${DOCKER_REGISTRY-}cardealerclient
    build:
      context: ./Clients/CarDealer.Client
      dockerfile: Dockerfile

  cardealer.db:
    image: mongo

